-- Requires an administrator authorized to create/manage these dedicated roles.
-- Review all statements. No role is assigned to any user by this script.
-- Use fresh roles; inherited/custom grants may defeat this reference boundary.
CREATE ROLE IF NOT EXISTS CHAINSCOPE_OPS;
CREATE ROLE IF NOT EXISTS CHAINSCOPE_COMMERCIAL;
GRANT USAGE ON DATABASE CHAINSCOPE_DEMO TO ROLE CHAINSCOPE_OPS;
GRANT USAGE ON SCHEMA CHAINSCOPE_DEMO.CORE TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON SEMANTIC VIEW CHAINSCOPE_DEMO.CORE.CHAINSCOPE_OPERATIONS TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_orders_ops TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_order_lines_ops TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_shipments TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_inventory TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_part_sources TO ROLE CHAINSCOPE_OPS;
-- Nonfinancial source tables support inspectable record-level evidence.
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.snapshot TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.suppliers TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.parts TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.plants TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.customers TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.sourcing TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.inventory TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.shipments TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.orders TO ROLE CHAINSCOPE_OPS;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.allocations TO ROLE CHAINSCOPE_OPS;
-- Never grant raw order_lines or v_orders to operations.
GRANT ROLE CHAINSCOPE_OPS TO ROLE CHAINSCOPE_COMMERCIAL;
GRANT SELECT ON SEMANTIC VIEW CHAINSCOPE_DEMO.CORE.CHAINSCOPE_COMMERCIAL TO ROLE CHAINSCOPE_COMMERCIAL;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_orders TO ROLE CHAINSCOPE_COMMERCIAL;
GRANT SELECT ON VIEW CHAINSCOPE_DEMO.CORE.v_order_lines TO ROLE CHAINSCOPE_COMMERCIAL;
GRANT SELECT ON TABLE CHAINSCOPE_DEMO.CORE.order_lines TO ROLE CHAINSCOPE_COMMERCIAL;
-- Admin must separately grant USAGE on an approved existing warehouse and the
-- necessary Cortex database role(s), then assign these roles to approved users.
